// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASjMAhZfWQbqTYtXo2sskLVNsY-66V9qY',
    appId: '1:1000029945820:web:10da52ed6ff9c9c835d919',
    messagingSenderId: '1000029945820',
    projectId: 'prodproductlist',
    authDomain: 'prodproductlist.firebaseapp.com',
    storageBucket: 'prodproductlist.firebasestorage.app',
    measurementId: 'G-MXLQWCTG4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiLeGSC1i_ICtltWN8qdawzkst6Khg3lY',
    appId: '1:1000029945820:android:2edbf71d63ceb59635d919',
    messagingSenderId: '1000029945820',
    projectId: 'prodproductlist',
    storageBucket: 'prodproductlist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9IMzxbH2yRK6JlxRk67fq-2I37pc96Q',
    appId: '1:1000029945820:ios:85ff16c54fc5463135d919',
    messagingSenderId: '1000029945820',
    projectId: 'prodproductlist',
    storageBucket: 'prodproductlist.firebasestorage.app',
    iosBundleId: 'com.example.productListingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9IMzxbH2yRK6JlxRk67fq-2I37pc96Q',
    appId: '1:1000029945820:ios:85ff16c54fc5463135d919',
    messagingSenderId: '1000029945820',
    projectId: 'prodproductlist',
    storageBucket: 'prodproductlist.firebasestorage.app',
    iosBundleId: 'com.example.productListingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASjMAhZfWQbqTYtXo2sskLVNsY-66V9qY',
    appId: '1:1000029945820:web:29115e1d9a02ce7d35d919',
    messagingSenderId: '1000029945820',
    projectId: 'prodproductlist',
    authDomain: 'prodproductlist.firebaseapp.com',
    storageBucket: 'prodproductlist.firebasestorage.app',
    measurementId: 'G-HRWCHB5TFC',
  );
}
